#!/usr/bin/env python3
"""Regenerate Codex skills from hmigbot's commands/*.md — the single source.

hmigbot (Claude Code plugin) keeps `commands/<name>.md`; this repo ships the
same text as `skills/<name>/SKILL.md`. Do NOT hand-edit the generated
SKILL.md files — edit the hmigbot command and re-run:

    python3 scripts/sync-commands.py --src ../migbot/commands            # write
    python3 scripts/sync-commands.py --src ../migbot/commands --check    # CI-style diff

Host adaptation is confined to this file (mechanical, reviewable):
  * `/a2h-*` slash commands -> `$a2h-*` skill mentions; `$ARGUMENTS` -> prose
  * bare `a2h-bootstrap` / `a2h-agreement` (on PATH in the plugin) ->
    `bash .migbot/bin/...` (staged by install.sh here)
  * plugin-mode sentences -> install.sh-mode sentences (PHRASES table)
  * Claude-Code-only OTel cleanup steps stripped (migbot telemetry is
    single-channel; Codex has no `.claude/settings.json`)
  * Codex-only `hook-trust` self-check paragraph injected into a2h-init
  * frontmatter: allowed-tools dropped, name + trigger added
Anything else that differs between the two hosts is a bug — keep the source
host-neutral instead of adding rules here.
"""
import argparse, difflib, os, re, sys

# Commands regenerated by default. The other converted commands (a2h-run,
# a2h-build, migbot-increment-*) have diverged by hand and are NOT in this
# list yet — add them once their Codex edits are backported to the source.
DEFAULT = ["a2h-init", "a2h-init-zh", "a2h-privacy", "a2h-privacy-zh"]

NAMES = (
    "a2h-init-zh", "a2h-init", "a2h-run-zh", "a2h-run", "a2h-build-zh", "a2h-build",
    "a2h-privacy-zh", "a2h-privacy", "a2h-spec", "a2h-plan", "a2h-execute",
    "a2h-verify", "a2h-retrospect",
    "migbot-increment-init", "migbot-increment-workflow",
    "migbot-increment-review", "migbot-increment-archive",
)
SLASH = re.compile(r"(?<![A-Za-z0-9/_$])/(?:" + "|".join(re.escape(n) for n in NAMES) + r")")

# Plugin-mode sentence -> install.sh-mode sentence (applied BEFORE slash->$).
PHRASES = [
    ("First run `Bash: a2h-bootstrap --lang <zh|en>` (the plugin's `bin/` is on PATH, so it is invokable as a bare command). This is **idempotent** and plays the role install.sh does in the non-plugin distribution:",
     "First run `Bash: bash .migbot/bin/a2h-bootstrap --lang <zh|en>` (`.migbot/bin` is staged by `install.sh`/`install.ps1`). This is **idempotent** and plays the role install.sh does:"),
    ("- If `a2h-bootstrap` is unavailable (the migbot plugin is not enabled) **and** the file does not exist, stop and tell the user: `\"migbot plugin runtime not found. Make sure the migbot plugin is enabled, then re-run /a2h-init.\"`",
     "- If `a2h-bootstrap` is unavailable (install was not run) **and** the file does not exist, stop and tell the user: `\"migbot runtime not found. Run migbot's install.sh / install.ps1 against this project, then re-run /a2h-init.\"`"),
    ("In plugin mode there is no install-time prompt, so on a **first run** a2h-init runs that exact flow inline (§2.2) right here at the start — it shows the full agreement and asks for the decision before anything else. For an already-decided state it just notes the state and moves on.",
     "`install.sh` / `install.ps1` try to collect the decision **at install time** — that runs in the user's real terminal, where the agreement popup CAN be raised. If they did, `.migbot/config.json` already shows `granted`/`denied` and §2.1 just notes it. Otherwise (unattended install, `--no-consent`, or a decision not yet made) a2h-init runs that exact flow inline (§2.2) on a **first run** — it shows the full agreement and asks for the decision before anything else. ⚠ Inside Codex's sandbox `a2h-agreement` **cannot pop a window** (LaunchServices/Explorer mach-lookups are denied), so the inline flow degrades to `shown:\"path\"` and the user must open the file manually — which is why install-time collection is preferred. For an already-decided state it just notes the state and moves on."),
    ("Reinstall the migbot plugin or contact the operator.", "Re-run migbot's install.sh / install.ps1, or contact the operator."),
    ("先跑 `Bash: a2h-bootstrap --lang <zh|en>`（plugin 的 `bin/` 在 PATH 上，可作裸命令直接调用）。它**幂等**，在 plugin 模式下扮演 install.sh 的角色：",
     "先跑 `Bash: bash .migbot/bin/a2h-bootstrap --lang <zh|en>`（`.migbot/bin` 由 `install.sh`/`install.ps1` 就位）。它**幂等**，扮演 install.sh 的角色："),
    ("- 若 `a2h-bootstrap` 不可用（migbot plugin 未启用）**且**文件不存在 → 停下并告诉用户：`\"未找到 migbot plugin 运行时。请确认 migbot plugin 已启用，然后重新运行 /a2h-init。\"`",
     "- 若 `a2h-bootstrap` 不可用（未跑过 install）**且**文件不存在 → 停下并告诉用户：`\"未找到 migbot 运行时。请对本工程跑 migbot 的 install.sh / install.ps1，然后重新运行 /a2h-init。\"`"),
    ("plugin 模式没有安装期询问，所以**首次运行**时 a2h-init 会在最开始就**就地内联执行那套流程**（§2.2）——先展示协议全文、征询用户选择，再做其它任何事。已决定状态则只告知并继续。",
     "`install.sh` / `install.ps1` 会尝试在**安装期**采集这个决定——安装脚本跑在用户真实终端里，协议弹窗**能**弹出来。若已采集，`.migbot/config.json` 里就已经是 `granted`/`denied`，§2.1 只做告知。否则（无人值守安装、`--no-consent`、或尚未决定），**首次运行**时 a2h-init 会在最开始就**就地内联执行那套流程**（§2.2）——先展示协议全文、征询用户选择，再做其它任何事。⚠ 在 Codex 沙箱内 `a2h-agreement` **弹不出窗口**（LaunchServices/Explorer 的 mach-lookup 被拒），内联流程会降级为 `shown:\"path\"`、要求用户手动打开文件——正因如此，**优先在安装期采集**。已决定状态则只告知并继续。"),
    ("请重装 migbot plugin 或联系运营方。", "请重跑 migbot 的 install.sh / install.ps1，或联系运营方。"),
]

HOOK_TRUST = {
    "en": "**Hook trust self-check (Codex-only, never blocks).** Run `Bash: .migbot/bin/a2h hook-trust`. Codex ≥ 0.129 silently skips any lifecycle hook the user has not trusted in `/hooks` (and does not load the project `.codex` layer at all until the project is trusted), so a migration can run end-to-end with **zero telemetry and no error**. If the command exits non-zero, relay its `RESULT:` line to the user verbatim and add: *\"Until you run `/hooks` in Codex and trust the migbot hooks, nothing from this migration is uploaded. You can re-check with `.migbot/bin/a2h hook-trust`.\"* Then continue — do not wait for them to fix it.\n\n",
    "zh": "**hook 信任自检（仅 Codex，绝不阻塞）。** 跑 `Bash: .migbot/bin/a2h hook-trust --lang zh`。Codex ≥ 0.129 会**静默跳过**用户没在 `/hooks` 里信任过的生命周期 hook（项目未被信任时，整个项目层 `.codex` 配置连同 hooks 都不加载），于是一次迁移可以从头跑到尾却**零遥测、零报错**。若命令退出码非 0，把它的 `RESULT:` 那行原样转述给用户，并补一句：*\"在 Codex 里运行 `/hooks` 并信任 migbot 的 hook 之前，本次迁移不会上传任何数据；随时可用 `.migbot/bin/a2h hook-trust --lang zh` 复查。\"* 然后继续流程——不要等用户处理。\n\n",
}
HOOK_ANCHOR = {"en": re.compile(r"^- Parse these fields:[^\n]*\n\n", re.M),
               "zh": re.compile(r"^- 解析这些字段：[^\n]*\n\n", re.M)}

DP = {
    "a2h-init": "Run the $a2h-init flow now: provision the runtime, run the User Experience Improvement Plan consent flow, confirm the android/harmonyos/deveco/hvigorw/adb/hdc paths, and set confirmed:true. Treat any user input as ignored.",
    "a2h-privacy": "Run $a2h-privacy now. Treat the user's input as the argument and dispatch to status (empty) / accept / deny / off.",
}
DP_ZH = {
    "a2h-init": "立即执行 $a2h-init 流程：就位运行时、跑《用户体验改进计划》同意流程、确认 android/harmonyos/deveco/hvigorw/adb/hdc 路径，置 confirmed:true。用户输入忽略。",
    "a2h-privacy": "立即执行 $a2h-privacy。把用户输入当作参数，分派到 status（空）/ accept / deny / off。",
}


def parse_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not m:
        return {}, text
    fm, cur = {}, None
    for line in m.group(1).splitlines():
        m2 = re.match(r"^([a-zA-Z_-]+):\s*(.*)$", line)
        if m2:
            cur = m2.group(1); fm[cur] = m2.group(2).strip()
        elif cur and re.match(r"^\s+", line):
            fm[cur] += " " + line.strip()
    return fm, m.group(2)


def strip_otel(body):
    # Bulleted / numbered OTel cleanup steps (Claude Code only).
    body = re.sub(r"^[ \t]*- \*\*Clean up legacy OTel export config[^\n]*\n", "", body, flags=re.M)
    body = re.sub(r"^[ \t]*Then \*\*clean up legacy OTel export config[^\n]*\n\n", "", body, flags=re.M)
    # Numbered step: drop it and renumber the next step in the same list.
    pat = re.compile(r"^(\d+)\. \*\*(?:Clean up legacy OTel export config|清理遗留 OTel 配置)[^\n]*\n", re.M)
    while True:
        m = pat.search(body)
        if not m:
            break
        n = int(m.group(1))
        rest = body[m.end():]
        rest = re.sub(r"^%d\. " % (n + 1), "%d. " % n, rest, count=1, flags=re.M)
        body = body[:m.start()] + rest
    return body


def convert(name, text):
    lang = "zh" if name.endswith("-zh") else "en"
    fm, body = parse_frontmatter(text)
    desc = re.sub(r"^\|[-+]?\s*", "", fm.get("description", "")).strip()
    for old, new in PHRASES:
        body = body.replace(old, new)
    body = body.replace("${CLAUDE_PLUGIN_ROOT}", "${PLUGIN_ROOT}").replace("CLAUDE.md", "AGENTS.md")
    body = body.replace(".claude/skills/", ".agents/skills/")
    body = re.sub(r"(?<=Bash: )a2h-bootstrap", "bash .migbot/bin/a2h-bootstrap", body)
    body = re.sub(r"(?<=Bash: )a2h-agreement", "bash .migbot/bin/a2h-agreement", body)
    body = SLASH.sub(lambda m: "$" + m.group(0)[1:], body)
    arg = "用户本次输入（作为命令参数）" if lang == "zh" else "the user's input (the command argument)"
    body = body.replace("`$ARGUMENTS`", arg).replace("$ARGUMENTS", arg)
    body = strip_otel(body)
    if name.startswith("a2h-init"):
        body, n = HOOK_ANCHOR[lang].subn(lambda m: m.group(0) + HOOK_TRUST[lang], body, count=1)
        if n != 1:
            sys.exit("hook-trust anchor not found in %s" % name)
    trigger = ("触发：`$%s` 或自然语言。" % name) if lang == "zh" else ("Trigger: `$%s` or natural language. " % name)
    head = ("---\nname: %s\ndescription: %s%s\n---\n\n" % (name, trigger, desc)
            + "> Codex skill (converted from the `%s` slash command). Invoke with `$%s`, or pick it in `/skills` (the default_prompt below auto-runs). Codex has no custom slash commands, so the `$` prefix replaces `/`.\n\n" % (name, name))
    return head + body.rstrip() + "\n"


def openai_yaml(name):
    base = name[:-3] if name.endswith("-zh") else name
    dp = DP_ZH.get(base) if name.endswith("-zh") else DP.get(base)
    if not dp:
        return None
    return ("# openai.yaml — Codex skill interface for the converted `%s` command.\n"
            "# When the user selects this skill in /skills, `interface.default_prompt` is\n"
            "# auto-attached — the Codex equivalent of running the slash command.\n"
            "interface:\n  display_name: \"%s\"\n  default_prompt: |\n    %s\n\npolicy:\n  allow_implicit_invocation: true\n" % (name, name, dp))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, help="path to hmigbot's commands/ directory")
    ap.add_argument("--dst", default=os.path.join(os.path.dirname(__file__), "..", "skills"))
    ap.add_argument("--only", default=",".join(DEFAULT))
    ap.add_argument("--check", action="store_true", help="diff instead of write; exit 1 on drift")
    a = ap.parse_args()
    drift = 0
    for name in [n for n in a.only.split(",") if n]:
        src = os.path.join(a.src, name + ".md")
        with open(src, encoding="utf-8") as f:
            out = convert(name, f.read())
        d = os.path.join(a.dst, name)
        dst = os.path.join(d, "SKILL.md")
        cur = open(dst, encoding="utf-8").read() if os.path.exists(dst) else ""
        if a.check:
            if cur != out:
                drift += 1
                sys.stdout.writelines(difflib.unified_diff(cur.splitlines(True), out.splitlines(True), dst, src + " (converted)"))
            else:
                print("ok:", dst)
            continue
        os.makedirs(os.path.join(d, "agents"), exist_ok=True)
        with open(dst, "w", encoding="utf-8", newline="\n") as f:
            f.write(out)
        y = os.path.join(d, "agents", "openai.yaml")
        if not os.path.exists(y) and openai_yaml(name):
            with open(y, "w", encoding="utf-8", newline="\n") as f:
                f.write(openai_yaml(name))
        print("wrote:", dst, "(changed)" if cur != out else "(unchanged)")
    if drift:
        sys.exit("%d skill(s) drifted from hmigbot commands/ — regenerate with sync-commands.py" % drift)


if __name__ == "__main__":
    main()
